spring:
  application:
    name: MagicFridgeAI
  # H2 Configuration
  datasource:
    url: ${DATABASE_URL}
    driver: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show:
      sql:
        true
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
  # OpenAI Configuration
  chatgpt:
    api:
      url: https://api.openai.com/v1/responses
      key: ${API_KEY}